[package]
name = "wasm-wrap-macro"
version = "0.1.0"
edition = "2024"
authors = ["En Shih <seanstone5923@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
